const defaultProducts = [
  {id:1,name:"Noise ColorFit smartwatch",category:"Electronics",price:1499,old:2999,discount:"50% off",rating:"4.4",reviews:"1,240",emoji:"⌚",color:"#eaf4ff",tag:"Bestseller"},
  {id:2,name:"Premium cotton t-shirt",category:"Fashion",price:499,old:999,discount:"50% off",rating:"4.3",reviews:"892",emoji:"👕",color:"#fff1e8",tag:"Top pick"},
  {id:3,name:"Fresh organic vegetables",category:"Grocery",price:299,old:399,discount:"25% off",rating:"4.7",reviews:"634",emoji:"🥦",color:"#e8f8ed",tag:"Fresh today"},
  {id:4,name:"JBL wireless headphones",category:"Electronics",price:1999,old:3499,discount:"43% off",rating:"4.5",reviews:"2,108",emoji:"🎧",color:"#f0edff",tag:"Hot deal"},
  {id:5,name:"Everyday running shoes",category:"Fashion",price:899,old:1799,discount:"50% off",rating:"4.2",reviews:"710",emoji:"👟",color:"#fff4d9",tag:"Trending"},
  {id:6,name:"Ceramic coffee mug set",category:"Home",price:599,old:999,discount:"40% off",rating:"4.6",reviews:"438",emoji:"☕",color:"#fcecf2",tag:"New"},
  {id:7,name:"Glow skincare essentials",category:"Beauty",price:749,old:1199,discount:"37% off",rating:"4.5",reviews:"521",emoji:"🧴",color:"#e9f7f7",tag:"Bestseller"},
  {id:8,name:"Smart LED desk lamp",category:"Home",price:899,old:1499,discount:"40% off",rating:"4.4",reviews:"315",emoji:"💡",color:"#fff6d8",tag:"Top pick"}
];
const storedProducts = JSON.parse(localStorage.getItem("atul-products") || "null");
const products = storedProducts || defaultProducts;
const state = {
  category:"All", search:"", cart:JSON.parse(localStorage.getItem("atul-cart") || "[]"),
  user:JSON.parse(localStorage.getItem("atul-user") || "null"), authMode:"login",
  orders:JSON.parse(localStorage.getItem("atul-orders") || "[]")
};
const $ = (selector) => document.querySelector(selector);
const grid = $("#product-grid"), emptyState = $("#empty-state"), toast = $("#toast"), cartDrawer = $("#cart-drawer"), overlay = $("#overlay");
const rupees = (value) => `₹${value.toLocaleString("en-IN")}`;
const save = () => { localStorage.setItem("atul-cart", JSON.stringify(state.cart)); localStorage.setItem("atul-orders", JSON.stringify(state.orders)); localStorage.setItem("atul-products", JSON.stringify(products)); };
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2400)}
function filteredProducts(){return products.filter((product)=>{const categoryMatch=state.category==="All"||product.category===state.category;const query=state.search.toLowerCase();return categoryMatch&&(!query||`${product.name} ${product.category}`.toLowerCase().includes(query))})}
function renderProducts(){const visible=filteredProducts();grid.innerHTML=visible.map((product)=>`<article class="product-card" data-product="${product.id}"><div class="product-image" style="background:${product.color}"><span>${product.emoji}</span><label class="tag">${product.tag}</label><button class="wishlist" aria-label="Add ${product.name} to wishlist">♡</button></div><div class="product-info"><div class="product-category">${product.category}</div><div class="product-name">${product.name}</div><span class="rating">★ ${product.rating}</span><span class="reviews">(${product.reviews})</span><div class="price-row"><span class="price">${rupees(product.price)}</span><span class="old-price">${rupees(product.old)}</span><span class="discount">${product.discount}</span></div><button class="add-btn" data-add="${product.id}">Add to cart</button></div></article>`).join("");emptyState.hidden=visible.length>0}
function updateAccount(){ $("#account-label").textContent=state.user?state.user.name.split(" ")[0]:"Login"; }
function updateCart(){const count=state.cart.reduce((sum,item)=>sum+item.quantity,0);$("#cart-count").textContent=count;$("#drawer-count").textContent=count;const total=state.cart.reduce((sum,item)=>sum+item.price*item.quantity,0);$("#cart-total").textContent=rupees(total);$("#checkout-total").textContent=rupees(total);$("#cart-items").innerHTML=state.cart.length?state.cart.map((item)=>`<div class="cart-row"><div class="cart-row-image" style="background:${item.color}">${item.emoji}</div><div class="cart-row-info"><strong>${item.name}</strong><small>${rupees(item.price)} each</small><div class="quantity"><button data-decrease="${item.id}">−</button><span>${item.quantity}</span><button data-increase="${item.id}">+</button></div></div><span class="cart-row-price">${rupees(item.price*item.quantity)}</span></div>`).join(""):'<div class="cart-empty">Your cart is waiting for good things ✨</div>';save()}
function openCart(){cartDrawer.classList.add("open");overlay.classList.add("show")}
function closeCart(){cartDrawer.classList.remove("open");overlay.classList.remove("show")}
function openModal(id){$(id).classList.add("open");$(id).setAttribute("aria-hidden","false")}
function closeModal(id){$(id).classList.remove("open");$(id).setAttribute("aria-hidden","true")}
function addToCart(id){const product=products.find((item)=>item.id===Number(id));const existing=state.cart.find((item)=>item.id===product.id);if(existing)existing.quantity+=1;else state.cart.push({...product,quantity:1});updateCart();showToast(`${product.name} added to your cart`)}
function renderDetail(product){$("#product-detail").innerHTML=`<div class="detail-layout"><div class="detail-image" style="background:${product.color}">${product.emoji}</div><div class="detail-copy"><span class="product-category">${product.category}</span><h2>${product.name}</h2><span class="rating">★ ${product.rating}</span> <span class="reviews">${product.reviews} verified ratings</span><div class="detail-price">${rupees(product.price)} <del>${rupees(product.old)}</del> <b>${product.discount}</b></div><p>Quality checked by Atul Cart. Get fast delivery, secure packaging and easy 7-day returns on this product.</p><ul><li>Free delivery on eligible orders</li><li>7-day easy replacement</li><li>Pay securely or choose COD</li></ul><button class="primary-btn" data-detail-add="${product.id}">Add to cart <span>→</span></button></div></div>`;openModal("#product-modal")}
function renderOrders(){const list=$("#orders-list");list.innerHTML=state.orders.length?state.orders.slice().reverse().map((order)=>`<div class="order-item"><div><strong>Order #${order.id}</strong><small>${order.date} · ${order.items} item(s)</small></div><b>${rupees(order.total)}</b><span class="order-status">${order.status}</span></div>`).join(""):'<div class="cart-empty">No orders yet. Your next great find is waiting.</div>'}
function renderAdmin(){const revenue=state.orders.reduce((sum,order)=>sum+order.total,0);$("#admin-stats").innerHTML=`<div><strong>${products.length}</strong><small>Products</small></div><div><strong>${state.orders.length}</strong><small>Orders</small></div><div><strong>${rupees(revenue)}</strong><small>Revenue</small></div>`;$("#admin-table").innerHTML=`<h3>Inventory</h3>${products.map((p)=>`<div class="admin-row"><span>${p.emoji} ${p.name}</span><b>${rupees(p.price)}</b><small>In stock</small></div>`).join("")}`}
$("#search-form").addEventListener("submit",(event)=>{event.preventDefault();state.search=$("#search-input").value.trim();renderProducts();$("#products").scrollIntoView({behavior:"smooth"})});
$("#search-input").addEventListener("input",(event)=>{state.search=event.target.value.trim();renderProducts()});
$(".categories").addEventListener("click",(event)=>{const button=event.target.closest("[data-category]");if(!button)return;state.category=button.dataset.category;document.querySelectorAll(".category-item").forEach((item)=>item.classList.toggle("active",item===button));renderProducts()});
grid.addEventListener("click",(event)=>{const addButton=event.target.closest("[data-add]");if(addButton){addToCart(addButton.dataset.add);return}const card=event.target.closest("[data-product]");if(card)renderDetail(products.find((item)=>item.id===Number(card.dataset.product)))});
$("#cart-items").addEventListener("click",(event)=>{const action=event.target.closest("[data-increase],[data-decrease]");if(!action)return;const id=Number(action.dataset.increase||action.dataset.decrease),item=state.cart.find((cartItem)=>cartItem.id===id);if(action.dataset.increase)item.quantity+=1;else if(item.quantity===1)state.cart=state.cart.filter((cartItem)=>cartItem.id!==id);else item.quantity-=1;updateCart()});
$("#cart-btn").addEventListener("click",openCart);$("#close-cart").addEventListener("click",closeCart);overlay.addEventListener("click",closeCart);
$("#shop-now").addEventListener("click",()=>$("#products").scrollIntoView({behavior:"smooth"}));
$("#view-all").addEventListener("click",()=>{state.category="All";state.search="";$("#search-input").value="";document.querySelectorAll(".category-item").forEach((item)=>item.classList.toggle("active",item.dataset.category==="All"));renderProducts()});
document.querySelectorAll(".promo-card button").forEach((button)=>button.addEventListener("click",()=>{state.category=button.dataset.category;document.querySelectorAll(".category-item").forEach((item)=>item.classList.toggle("active",item.dataset.category===state.category));renderProducts();$("#products").scrollIntoView({behavior:"smooth"})}));
$("#account-btn").addEventListener("click",()=>{if(state.user){showToast(`Welcome back, ${state.user.name}`)}else openModal("#auth-modal")});
$("#orders-btn").addEventListener("click",()=>{renderOrders();openModal("#orders-modal")});
$("#admin-btn").addEventListener("click",()=>{renderAdmin();openModal("#admin-modal")});
document.addEventListener("click",(event)=>{const close=event.target.closest("[data-close-modal]");if(close)closeModal(`#${close.dataset.closeModal}`);const detailAdd=event.target.closest("[data-detail-add]");if(detailAdd){addToCart(detailAdd.dataset.detailAdd);closeModal("#product-modal")}});
document.querySelectorAll("[data-auth-tab]").forEach((tab)=>tab.addEventListener("click",()=>{state.authMode=tab.dataset.authTab;document.querySelectorAll("[data-auth-tab]").forEach((item)=>item.classList.toggle("active",item===tab));$("#auth-name").closest("label").style.display=state.authMode==="signup"?"block":"none";$("#auth-submit").innerHTML=state.authMode==="signup"?"Create account <span>→</span>":"Login securely <span>→</span>"}));
$("#auth-form").addEventListener("submit",(event)=>{event.preventDefault();const name=$("#auth-name").value.trim()||$("#auth-email").value.split("@")[0];state.user={name,email:$("#auth-email").value};localStorage.setItem("atul-user",JSON.stringify(state.user));updateAccount();closeModal("#auth-modal");showToast(state.authMode==="signup"?"Account created successfully":"Logged in successfully")});
$("#checkout-btn").addEventListener("click",()=>{if(!state.cart.length){showToast("Your cart is empty");return}closeCart();openModal("#checkout-modal")});
$("#checkout-form").addEventListener("submit",(event)=>{event.preventDefault();const form=new FormData(event.target),total=state.cart.reduce((sum,item)=>sum+item.price*item.quantity,0);state.orders.push({id:`AC${Date.now().toString().slice(-6)}`,date:new Date().toLocaleDateString("en-IN"),items:state.cart.reduce((sum,item)=>sum+item.quantity,0),total,status:"Confirmed"});state.cart=[];updateCart();event.target.reset();closeModal("#checkout-modal");showToast("Order placed successfully 🎉");renderOrders()});
document.querySelectorAll(".footer a").forEach((link)=>link.addEventListener("click",(event)=>{if(link.getAttribute("href")?.startsWith("#")){event.preventDefault();showToast("This page is coming soon")}}));
window.addEventListener("keydown",(event)=>{if(event.key==="Escape"){document.querySelectorAll(".modal-shell.open").forEach((modal)=>closeModal(`#${modal.id}`));closeCart()}});
renderProducts();updateCart();updateAccount();document.querySelector('[data-auth-tab="login"]').click();
