const SUPABASE_URL = "https://beplguuxcxhhcxrlrlfu.supabase.co";
const SUPABASE_KEY = "sb_publishable_wi0GQuyS_Zx8UwHCBdFFSQ_PfHxbzTm";
const defaultProducts = [
  {id:1,name:"Noise ColorFit smartwatch",category:"Electronics",price:1499,old:2999,discount:"50% off",rating:"4.4",reviews:"1,240",emoji:"⌚",color:"#eaf4ff",tag:"Bestseller",stock:3,variants:["Black","Blue"],gallery:["⌚","⌚","⌚"]},
  {id:2,name:"Premium cotton t-shirt",category:"Fashion",price:499,old:999,discount:"50% off",rating:"4.3",reviews:"892",emoji:"👕",color:"#fff1e8",tag:"Top pick",stock:8,variants:["S","M","L","XL"],gallery:["👕","👕","👕"]},
  {id:3,name:"Fresh organic vegetables",category:"Grocery",price:299,old:399,discount:"25% off",rating:"4.7",reviews:"634",emoji:"🥦",color:"#e8f8ed",tag:"Fresh today",stock:12,gallery:["🥦","🥕","🥬"]},
  {id:4,name:"JBL wireless headphones",category:"Electronics",price:1999,old:3499,discount:"43% off",rating:"4.5",reviews:"2,108",emoji:"🎧",color:"#f0edff",tag:"Hot deal",stock:5,variants:["Black","White"],gallery:["🎧","🎧","🎧"]},
  {id:5,name:"Everyday running shoes",category:"Fashion",price:899,old:1799,discount:"50% off",rating:"4.2",reviews:"710",emoji:"👟",color:"#fff4d9",tag:"Trending",stock:9},
  {id:6,name:"Ceramic coffee mug set",category:"Home",price:599,old:999,discount:"40% off",rating:"4.6",reviews:"438",emoji:"☕",color:"#fcecf2",tag:"New",stock:10},
  {id:7,name:"Glow skincare essentials",category:"Beauty",price:749,old:1199,discount:"37% off",rating:"4.5",reviews:"521",emoji:"🧴",color:"#e9f7f7",tag:"Bestseller",stock:7},
  {id:8,name:"Smart LED desk lamp",category:"Home",price:899,old:1499,discount:"40% off",rating:"4.4",reviews:"315",emoji:"💡",color:"#fff6d8",tag:"Top pick",stock:6}
];
const storedProducts = JSON.parse(localStorage.getItem("atul-products") || "null");
const products = (Array.isArray(storedProducts) && storedProducts.length ? storedProducts : [...defaultProducts]).map((product) => ({
  ...product,
  stock: Number.isFinite(Number(product.stock)) ? Number(product.stock) : 10,
  reviews: String(product.reviews ?? "0")
}));
const state = {
  category:"All", search:"", cart:JSON.parse(localStorage.getItem("atul-cart") || "[]"),
  wishlist:JSON.parse(localStorage.getItem("atul-wishlist") || "[]"),
  user:JSON.parse(localStorage.getItem("atul-user") || "null"), isAdmin:false, profile:JSON.parse(localStorage.getItem("atul-profile") || "null"), wallet:Number(localStorage.getItem("atul-wallet") || 0), authMode:"login", sort:"popular", price:"all",
  orders:JSON.parse(localStorage.getItem("atul-orders") || "[]")
};
const $ = (selector) => document.querySelector(selector);
const grid = $("#product-grid"), emptyState = $("#empty-state"), toast = $("#toast"), cartDrawer = $("#cart-drawer"), overlay = $("#overlay");
const rupees = (value) => `₹${value.toLocaleString("en-IN")}`;
const save = () => { localStorage.setItem("atul-cart", JSON.stringify(state.cart)); localStorage.setItem("atul-orders", JSON.stringify(state.orders)); localStorage.setItem("atul-products", JSON.stringify(products)); localStorage.setItem("atul-wishlist", JSON.stringify(state.wishlist)); localStorage.setItem("atul-wallet", String(state.wallet)); if(state.profile)localStorage.setItem("atul-profile", JSON.stringify(state.profile)); };
async function loadProductsFromSupabase() {
  grid.classList.add("skeleton");
  try {
    const response = await fetch(`${SUPABASE_URL}/rest/v1/products?select=*&order=id`, {
      headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` }
    });
    if (!response.ok) throw new Error(`Products request failed with ${response.status}`);
    const remoteProducts = await response.json();
    if (remoteProducts.length) {
      products.splice(0, products.length, ...remoteProducts.map((product) => ({
        ...product,
        old: product.old_price,
        reviews: Number(product.reviews || 0).toLocaleString("en-IN"),
        stock: Number(product.stock ?? 10)
      })));
      renderProducts();
      renderPromoProducts();
    }
  } catch (error) {
    console.warn("Supabase products unavailable; using local catalogue.", error);
  } finally {
    grid.classList.remove("skeleton");
  }
}
function renderPromoProducts(){document.querySelectorAll("[data-promo-grid]").forEach((gridElement)=>{const category=gridElement.dataset.promoGrid;gridElement.innerHTML=products.filter((product)=>product.category===category).slice(0,3).map((product)=>`<button class="promo-product" data-promo-product="${product.id}"><span>${product.emoji}</span><small>${product.name}</small></button>`).join("")})}
async function saveOrderToSupabase(order, customer) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/orders`, {
    method: "POST",
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
      "Content-Type": "application/json",
      Prefer: "return=minimal"
    },
    body: JSON.stringify({
      id: order.uuid,
      customer_name: customer.name,
      phone: customer.phone,
      address: customer.address,
      city: customer.city,
      pin: customer.pin,
      payment_method: customer.payment,
      total: order.total,
      status: order.status,
      items: order.cart
    })
  });
  if (!response.ok) throw new Error(`Order request failed with ${response.status}`);
}
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2400)}
async function supabaseAuth(path, payload) {
  const response = await fetch(`${SUPABASE_URL}/auth/v1/${path}`, {
    method: "POST",
    headers: { apikey: SUPABASE_KEY, "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.msg || data.error_description || "OTP request failed");
  return data;
}
async function supabaseRequest(path, options = {}) {
  const headers = { apikey: SUPABASE_KEY, ...(options.headers || {}) };
  if (state.user?.accessToken) headers.Authorization = `Bearer ${state.user.accessToken}`;
  const response = await fetch(`${SUPABASE_URL}${path}`, { ...options, headers });
  if (!response.ok) throw new Error(`Supabase request failed with ${response.status}`);
  return response.status === 204 ? null : response.json();
}
async function signOut() {
  if (state.user?.accessToken) {
    const response = await fetch(`${SUPABASE_URL}/auth/v1/logout`, {
      method: "POST",
      headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${state.user.accessToken}` }
    });
    if (!response.ok && response.status !== 401) throw new Error(`Logout request failed with ${response.status}`);
  }
  state.user = null;
  state.isAdmin = false;
  state.profile = null;
  localStorage.removeItem("atul-user");
  localStorage.removeItem("atul-profile");
  $("#admin-btn").hidden = true;
  updateAccount();
  closeModal("#profile-modal");
  showToast("You have been logged out securely");
}
async function syncProfileToSupabase(profile) {
  if (!state.user?.id) return;
  await supabaseRequest("/rest/v1/profiles?on_conflict=user_id", {
    method: "POST",
    headers: { "Content-Type": "application/json", Prefer: "resolution=merge-duplicates,return=minimal" },
    body: JSON.stringify({ user_id: state.user.id, ...profile })
  });
}
async function loadProfileFromSupabase() {
  if (!state.user?.id) return;
  const rows = await supabaseRequest(`/rest/v1/profiles?select=name,phone,address,landmark,pin&user_id=eq.${encodeURIComponent(state.user.id)}&limit=1`);
  if (rows[0]) { state.profile = rows[0]; save(); }
}
function filteredProducts(){const list=products.filter((product)=>{const categoryMatch=state.category==="All"||product.category===state.category;const query=state.search.toLowerCase();const priceMatch=state.price==="all"||(state.price==="under500"&&product.price<500)||(state.price==="500to1000"&&product.price>=500&&product.price<=1000)||(state.price==="over1000"&&product.price>1000);return categoryMatch&&priceMatch&&(!query||`${product.name} ${product.category}`.toLowerCase().includes(query))});return list.sort((a,b)=>state.sort==="low"?a.price-b.price:state.sort==="high"?b.price-a.price:state.sort==="rating"?Number(b.rating)-Number(a.rating):Number(b.reviews.replace(",",""))-Number(a.reviews.replace(",","")))}
function renderProducts(){const visible=filteredProducts().filter((product)=>product.status!=="draft");grid.innerHTML=visible.map((product)=>{const saved=state.wishlist.includes(product.id),stock=Number(product.stock??0),available=stock>0;return `<article class="product-card ${available?"":"out-of-stock"}" data-product="${product.id}" aria-label="${product.name} product card"><div class="product-image ratio-box" role="img" aria-label="${product.name} image" style="background:${product.color}"><span>${product.emoji}</span><label class="tag badge-ribbon">${product.tag}</label><button class="wishlist ${saved?"saved":""}" data-wishlist="${product.id}" aria-label="${saved?"Remove":"Add"} ${product.name} ${saved?"from":"to"} wishlist">${saved?"♥":"♡"}</button></div><div class="product-info"><div class="product-category">${product.category}</div><div class="product-name">${product.name}</div><div class="star-rating-box"><span class="rating">★ ${product.rating}</span><span class="reviews">(${product.reviews})</span></div><div class="price-row price-split"><span class="price">${rupees(product.price)}</span><span class="old-price">${rupees(product.old)}</span><span class="discount">${product.discount}</span></div>${available?`<small class="stock-note">${stock<=3?`Only ${stock} left`:"In stock"}</small>`:"<small class=\"stock-note out-of-stock\">Out of stock</small>"}<button class="add-btn" data-add="${product.id}" ${available?"":"disabled"}>${available?"Add to cart":"Unavailable"}</button></div></article>`}).join("");emptyState.hidden=visible.length>0}
function updateAccount(){ $("#account-label").textContent=state.user?state.user.name.split(" ")[0]:"Login"; }
function updateCart(){const count=state.cart.reduce((sum,item)=>sum+item.quantity,0);$("#cart-count").textContent=count;$("#drawer-count").textContent=count;const total=state.cart.reduce((sum,item)=>sum+item.price*item.quantity,0);$("#cart-total").textContent=rupees(total);$("#checkout-total").textContent=rupees(total);$("#cart-items").innerHTML=state.cart.length?state.cart.map((item)=>`<div class="cart-row"><div class="cart-row-image" style="background:${item.color}">${item.emoji}</div><div class="cart-row-info"><strong>${item.name}</strong><small>${rupees(item.price)} each</small><div class="quantity"><button data-decrease="${item.id}">−</button><span>${item.quantity}</span><button data-increase="${item.id}">+</button></div></div><span class="cart-row-price">${rupees(item.price*item.quantity)}</span></div>`).join(""):'<div class="cart-empty">Your cart is waiting for good things ✨</div>';save()}
function openCart(){cartDrawer.classList.add("open");overlay.classList.add("show")}
function closeCart(){cartDrawer.classList.remove("open");overlay.classList.remove("show")}
function openModal(id){$(id).classList.add("open");$(id).setAttribute("aria-hidden","false")}
function closeModal(id){$(id).classList.remove("open");$(id).setAttribute("aria-hidden","true")}
function addToCart(id){const product=products.find((item)=>item.id===Number(id));if(!product||Number(product.stock??0)<1){showToast("This product is currently out of stock");return}const existing=state.cart.find((item)=>item.id===product.id);if(existing){if(existing.quantity>=Number(product.stock)){showToast(`Only ${product.stock} available`);return}existing.quantity+=1}else state.cart.push({...product,quantity:1});updateCart();showToast(`${product.name} added to your cart`)}
function renderDetail(product){const gallery=product.gallery||[product.emoji,product.emoji,product.emoji];$("#product-detail").innerHTML=`<div class="detail-layout"><div><div class="detail-image zoom-image ratio-box" role="img" aria-label="${product.name} image" style="background:${product.color}"><span id="detail-emoji">${gallery[0]}</span></div><div class="gallery-thumbs image-thumbnails">${gallery.map((image,index)=>`<button class="${index===0?"active":""}" data-gallery="${image}" aria-label="View image ${index+1}">${image}</button>`).join("")}</div><video class="product-video" preload="none" controls aria-label="${product.name} demo video"><track kind="captions" /></video></div><div class="detail-copy"><span class="product-category">${product.category}</span><h2>${product.name}</h2><div class="star-rating-box"><span class="rating">★ ${product.rating}</span> <span class="reviews">${product.reviews} verified ratings</span></div><div class="detail-price price-split">${rupees(product.price)} <del>${rupees(product.old)}</del> <b>${product.discount}</b></div><p class="stock-alert">Only ${product.stock||7} left in stock!</p>${product.variants?`<div class="variant-block"><strong>Select option</strong><div class="color-dot-selector">${product.variants.map((v,i)=>`<button class="variant ${i===0?"active":""}" aria-label="${v}">${v}</button>`).join("")}</div></div>`:""}<table class="specs-table"><tbody><tr><th>Category</th><td>${product.category}</td></tr><tr><th>Availability</th><td>${product.stock>0?"In stock":"Out of stock"}</td></tr></tbody></table><p>Quality checked by Atul Cart. Get fast delivery, secure packaging and easy 7-day returns on this product.</p><ul><li>Estimated delivery: <strong>${new Date(Date.now()+4*86400000).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</strong></li><li>7-day easy replacement</li><li>Cash on delivery available</li></ul><div class="detail-actions"><button class="primary-btn" data-detail-add="${product.id}">Add to cart <span>→</span></button><button class="secondary-btn" data-buy-now="${product.id}">Buy now</button></div><article class="review-card review-box"><strong>Customer reviews</strong><p>★★★★★ “Great quality and fast delivery.” — Verified buyer</p><button class="text-btn" data-review="${product.id}">Write a review</button></article></div></div>`;openModal("#product-modal")}
function renderOrders(){const list=$("#orders-list");list.innerHTML=state.orders.length?state.orders.slice().reverse().map((order)=>`<div class="order-item"><div><strong>Order #${order.id}</strong><small>${order.date} · ${order.items} item(s)</small></div><b>${rupees(order.total)}</b><span class="order-status">${order.status}</span><div class="order-actions">${order.status==="Order Placed"?`<button data-cancel-order="${order.id}">Cancel</button>`:""}<button data-reorder="${order.id}">Re-order</button><button data-invoice="${order.id}">Invoice</button></div></div>`).join(""):'<div class="cart-empty">No orders yet. Your next great find is waiting.</div>'}
function renderAdmin(){const revenue=state.orders.reduce((sum,order)=>sum+order.total,0),lowStock=products.filter((product)=>Number(product.stock??0)<=3).length,statuses=["Order Placed","Packed","Shipped","Out for delivery","Delivered","Cancelled","Returned","Refunded"];$("#admin-stats").innerHTML=`<div><strong>${products.length}</strong><small>Products</small></div><div><strong>${state.orders.length}</strong><small>Orders</small></div><div><strong>${rupees(revenue)}</strong><small>Revenue</small></div><div><strong>${lowStock}</strong><small>Low stock</small></div>`;$("#admin-table").innerHTML=`<h3>Inventory</h3>${products.map((p)=>`<div class="admin-row"><span>${p.emoji} ${p.name}${Number(p.stock??0)<=3?`<small class="low-stock">Low stock</small>`:""}</span><label>Price <input type="number" min="1" value="${p.price}" data-product-price="${p.id}" /></label><label>Stock <input type="number" min="0" value="${p.stock||0}" data-product-stock="${p.id}" /></label><button class="secondary-btn" data-save-product="${p.id}">Save</button></div>`).join("")}<h3>Orders</h3>${state.orders.length?state.orders.slice().reverse().map((order)=>`<div class="admin-row"><span>Order #${order.id}<small>${order.date} · ${rupees(order.total)}</small></span><select data-order-status="${order.id}" aria-label="Status for order ${order.id}">${statuses.map((status)=>`<option value="${status}" ${status===order.status?"selected":""}>${status}</option>`).join("")}</select><button class="secondary-btn" data-save-order="${order.id}">Update</button></div>`).join(""):'<p class="admin-empty">No orders yet.</p>'}`}
function addAdminProduct(form){const values=Object.fromEntries(new FormData(form));const price=Number(values.price),old=Number(values.old),stock=Number(values.stock),tax=Number(values.tax||0);if(!values.name||!values.category||!values.emoji||price<1||old<1||stock<0||tax<0||tax>100){showToast("Please enter valid product details");return}products.push({id:Date.now(),name:String(values.name).trim(),brand:String(values.brand||"").trim(),sku:String(values.sku||"").trim(),description:String(values.description||"").trim(),category:String(values.category).trim(),price,old,tax,discount:`${Math.max(0,Math.round((1-price/old)*100))}% off`,rating:"0",reviews:"0",emoji:String(values.emoji).trim(),color:"#eef4ff",tag:"New",status:String(values.status||"active"),stock, gallery:[String(values.emoji).trim()]});save();form.reset();renderAdmin();renderProducts();showToast("Product added successfully")}
function updateAdminProduct(id,row){const product=products.find((item)=>item.id===Number(id));if(!product)return;const price=Number(row.querySelector(`[data-product-price="${id}"]`).value),stock=Number(row.querySelector(`[data-product-stock="${id}"]`).value);if(!Number.isFinite(price)||price<1||!Number.isInteger(stock)||stock<0){showToast("Price or stock value is invalid");return}product.price=price;product.stock=stock;save();renderAdmin();renderProducts();showToast("Product updated successfully")}
function exportAdminOrders(){if(!state.isAdmin){showToast("Admin access is required");return}const escapeCsv=(value)=>`"${String(value??"").split('"').join('""')}"`,rows=[["Order ID","Date","Phone","Items","Total","Status"],...state.orders.map((order)=>[order.id,order.date,order.phone,order.items,order.total,order.status])],csv=rows.map((row)=>row.map(escapeCsv).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`atul-cart-orders-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);showToast("Orders CSV downloaded")}
async function loadAuthenticatedUser(accessToken){const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`}});if(!response.ok)throw new Error(`Authentication request failed with ${response.status}`);return response.json()}
async function verifyAdminAccess(){const adminButton=$("#admin-btn");state.isAdmin=false;adminButton.hidden=true;if(!state.user?.id||!state.user?.accessToken)return false;const response=await fetch(`${SUPABASE_URL}/rest/v1/admin_users?select=role&user_id=eq.${encodeURIComponent(state.user.id)}&role=eq.admin&limit=1`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.user.accessToken}`}});if(!response.ok)throw new Error(`Admin authorization request failed with ${response.status}`);const rows=await response.json();state.isAdmin=rows.length>0;adminButton.hidden=!state.isAdmin;return state.isAdmin}
$("#search-form").addEventListener("submit",(event)=>{event.preventDefault();state.search=$("#search-input").value.trim();renderProducts();$("#products").scrollIntoView({behavior:"smooth"})});
$("#search-input").addEventListener("input",(event)=>{state.search=event.target.value.trim();renderProducts()});
$("#sort-select").addEventListener("change",(event)=>{state.sort=event.target.value;renderProducts()});
document.querySelector(".filter-chips").addEventListener("click",(event)=>{const chip=event.target.closest("[data-price]");if(!chip)return;state.price=chip.dataset.price;document.querySelectorAll(".filter-chip").forEach((item)=>item.classList.toggle("active",item===chip));renderProducts()});
$(".categories").addEventListener("click",(event)=>{const button=event.target.closest("[data-category]");if(!button)return;state.category=button.dataset.category;document.querySelectorAll(".category-item").forEach((item)=>item.classList.toggle("active",item===button));renderProducts()});
grid.addEventListener("click",(event)=>{const wishlistButton=event.target.closest("[data-wishlist]");if(wishlistButton){event.stopPropagation();const id=Number(wishlistButton.dataset.wishlist),index=state.wishlist.indexOf(id);if(index===-1){state.wishlist.push(id);showToast("Added to your wishlist")}else{state.wishlist.splice(index,1);showToast("Removed from your wishlist")}save();renderProducts();return}const addButton=event.target.closest("[data-add]");if(addButton){event.stopPropagation();addToCart(addButton.dataset.add);return}const card=event.target.closest("[data-product]");if(card)renderDetail(products.find((item)=>item.id===Number(card.dataset.product)))});
$("#cart-items").addEventListener("click",(event)=>{const action=event.target.closest("[data-increase],[data-decrease]");if(!action)return;const id=Number(action.dataset.increase||action.dataset.decrease),item=state.cart.find((cartItem)=>cartItem.id===id),product=products.find((entry)=>entry.id===id);if(!item||!product)return;if(action.dataset.increase){if(item.quantity>=Number(product.stock??0)){showToast(`Only ${product.stock} available`);return}item.quantity+=1}else if(item.quantity===1)state.cart=state.cart.filter((cartItem)=>cartItem.id!==id);else item.quantity-=1;updateCart()});
$("#cart-btn").addEventListener("click",openCart);$("#close-cart").addEventListener("click",closeCart);overlay.addEventListener("click",closeCart);
$("#shop-now").addEventListener("click",()=>$("#products").scrollIntoView({behavior:"smooth"}));
const resetCatalog=()=>{state.category="All";state.search="";state.price="all";state.sort="popular";$("#search-input").value="";$("#sort-select").value="popular";document.querySelectorAll(".category-item").forEach((item)=>item.classList.toggle("active",item.dataset.category==="All"));document.querySelectorAll(".filter-chip").forEach((item)=>item.classList.toggle("active",item.dataset.price==="all"));renderProducts()};
$("#view-all").addEventListener("click",()=>{resetCatalog();$("#products").scrollIntoView({behavior:"smooth"})});
$("#reset-catalog").addEventListener("click",resetCatalog);
document.querySelectorAll(".promo-card button").forEach((button)=>button.addEventListener("click",()=>{state.category=button.dataset.category;document.querySelectorAll(".category-item").forEach((item)=>item.classList.toggle("active",item.dataset.category===state.category));renderProducts();$("#products").scrollIntoView({behavior:"smooth"})}));
$("#account-btn").addEventListener("click",()=>{if(state.user){const profile=state.profile||{name:state.user.name,phone:"",address:"",landmark:"",pin:""};Object.entries(profile).forEach(([key,value])=>{const field=$(`#profile-form [name="${key}"]`);if(field)field.value=value});$("#wallet-balance").textContent=rupees(state.wallet);openModal("#profile-modal")}else openModal("#auth-modal")});
$("#orders-btn").addEventListener("click",()=>{renderOrders();openModal("#orders-modal")});
$("#open-tracking").addEventListener("click",()=>{closeModal("#orders-modal");openModal("#tracking-modal")});
$("#admin-btn").addEventListener("click",async()=>{try{if(!await verifyAdminAccess()){showToast("Admin access is restricted to authorized accounts");return}renderAdmin();openModal("#admin-modal")}catch(error){console.error(error);showToast("Admin access could not be verified")}})
$("#product-form").addEventListener("submit",(event)=>{event.preventDefault();if(!state.isAdmin){showToast("Admin access is required");return}addAdminProduct(event.target)});
$("#admin-table").addEventListener("click",(event)=>{const button=event.target.closest("[data-save-product]");if(button){if(!state.isAdmin){showToast("Admin access is required");return}updateAdminProduct(button.dataset.saveProduct,button.closest(".admin-row"))}});
$("#admin-table").addEventListener("click",(event)=>{const button=event.target.closest("[data-save-order]");if(!button){return}if(!state.isAdmin){showToast("Admin access is required");return}const order=state.orders.find((item)=>item.id===button.dataset.saveOrder),select=button.closest(".admin-row").querySelector(`[data-order-status="${button.dataset.saveOrder}"]`);if(!order||!select){showToast("Order could not be found");return}order.status=select.value;save();renderAdmin();renderOrders();showToast(`Order ${order.id} status updated`)});
$("#export-orders").addEventListener("click",exportAdminOrders);
$("#profile-form").addEventListener("submit",async(event)=>{event.preventDefault();state.profile=Object.fromEntries(new FormData(event.target));state.user={...(state.user||{}),name:state.profile.name};localStorage.setItem("atul-user",JSON.stringify(state.user));try{await syncProfileToSupabase(state.profile);updateAccount();save();showToast("Profile and address saved")}catch(error){console.error(error);showToast("Profile local mein save hua, cloud sync failed")}});
$("#profile-orders").addEventListener("click",()=>{closeModal("#profile-modal");renderOrders();openModal("#orders-modal")});
$("#logout-btn").addEventListener("click",async()=>{try{await signOut()}catch(error){console.error(error);showToast("Logout could not be completed")}}); 
$("#orders-list").addEventListener("click",(event)=>{const cancel=event.target.closest("[data-cancel-order]");const reorder=event.target.closest("[data-reorder]");const invoice=event.target.closest("[data-invoice]");if(cancel){const order=state.orders.find((item)=>item.id===cancel.dataset.cancelOrder);order.status="Cancelled";state.wallet+=Math.round(order.total*.02);save();renderOrders();showToast("Order cancelled; cashback added to wallet")}if(reorder){const order=state.orders.find((item)=>item.id===reorder.dataset.reorder);(order.cart||[]).forEach((item)=>addToCart(item.id));closeModal("#orders-modal");openCart()}if(invoice){const order=state.orders.find((item)=>item.id===invoice.dataset.invoice);const invoiceWindow=window.open("","_blank");if(invoiceWindow){invoiceWindow.document.write(`<h1>Atul Cart Invoice</h1><p>Order: ${order.id}</p><p>Date: ${order.date}</p><p>Total: ${rupees(order.total)}</p><p>Payment: Cash on delivery</p>`);invoiceWindow.print()}}});
$("#delivery-btn").addEventListener("click",()=>openModal("#location-modal"));
$("#location-form").addEventListener("submit",(event)=>{event.preventDefault();const pin=String(new FormData(event.target).get("pin")||"").trim(),supported=/^(2718|283|110|201|226|229|244|250|261|262|273|274|275|276|277|278|279|281|282|284|285|286|287|288|289|301|302|303|304|305|306|307|308|309|310|311|312|313|314|321|322|323|324|325|326|327|328|329|331|332|333|334|335|341|342|343|344|345|346|347|360|361|362|363|364|365|380|390|400|401|411|412|413|421|422|423|424|425|431|452|462|471|482|492|560|561|562|563|570|571|572|573|574|575|576|577|578|580|581|582|583|585|586|587|588|589|590|591|600|601|602|603|604|605|606|607|608|609|610|611|612|613|614|615|616|617|618|620|621|622|623|624|625|626|627|628|629|630|631|632|633|641|642|643|644|645|646|647|652|653|670|671|673|674|675|676|677|678|679|680|681|682|683|685|686|700|701|702|703|704|705|706|707|708|709|710|711|712|713|714|715|716|717|718|719|721|722|723|724|725|726|727|728|729|731|732|733|734|735|736|737|741|742|743|744|745|746|747|748|749|751|752|753|754|755|756|757|758|759|760|761|762|763|764|765|766|767|768|769|770|771|781|782|783|784|785|786|787|788|789|790|791|792|793|794|795|796|797|798|799|800|801|802|803|804|805|806|807|808|809|810|811|812|813|814|815|816|817|818|819|820|821|822|823|824|825|826|827|828|829|830|831|832|833|834|835|836|841|842|843|844|845|846|847|851|852|853|854|855|856|857|858|859|860|861|862|863|864|865|866|867|868|869|870|871|872|873|874|875|876|877|878|879|880|881|882|883|884|885|886|887|888|889|890|891|892|893|894|895|896|897|898|899)$/i.test(pin);if(!supported){showToast("COD delivery is not available for this PIN yet");return}$("#delivery-label").textContent=pin;closeModal("#location-modal");showToast(`COD delivery available for ${pin}`)});
$("#sell-btn").addEventListener("click",()=>showToast("Seller registration is coming soon"));
const policyContent={returns:["Returns & refunds","Request a return within 7 days for eligible products. COD refunds are added to your Atul Wallet after inspection."],terms:["Terms & conditions","Atul Cart provides COD shopping, product availability may change, and delivery depends on the selected PIN code."],privacy:["Privacy policy","We use your account, address and order details only to process delivery, support and account features. Never share your OTP."],shipping:["Shipping policy","Delivery is available on supported PIN codes. Estimated delivery is shown during checkout and may vary by location."],cancellation:["Cancellation policy","You can cancel an order before it is packed. Eligible refunds are credited to your Atul Wallet after review."],contact:["Contact us","Call 8795484365, email singhatulkumar8795@gmail.com, or use WhatsApp support for help."]};
document.querySelectorAll(".footer a[data-policy]").forEach((link)=>link.addEventListener("click",(event)=>{event.preventDefault();const policy=policyContent[link.dataset.policy];$("#policy-title").textContent=policy[0];$("#policy-content").textContent=policy[1];openModal("#policy-modal")}));
document.querySelectorAll("[data-chat]").forEach((button)=>button.addEventListener("click",()=>{$("#chat-message").textContent={delivery:"COD delivery is available on supported PIN codes and usually arrives in 3–5 business days.",returns:"Eligible products can be returned within 7 days after delivery.",order:"Open Orders to see your saved order status or use Track an order."}[button.dataset.chat];$("#chat-box").classList.add("open")}));
document.addEventListener("click",(event)=>{const close=event.target.closest("[data-close-modal]");if(close)closeModal(`#${close.dataset.closeModal}`);const promoProduct=event.target.closest("[data-promo-product]");if(promoProduct)renderDetail(products.find((item)=>item.id===Number(promoProduct.dataset.promoProduct)));const gallery=event.target.closest("[data-gallery]");if(gallery){$("#detail-emoji").textContent=gallery.dataset.gallery;document.querySelectorAll(".gallery-thumbs button").forEach((item)=>item.classList.toggle("active",item===gallery))}const variant=event.target.closest(".variant");if(variant){document.querySelectorAll(".variant").forEach((item)=>item.classList.toggle("active",item===variant))}const detailAdd=event.target.closest("[data-detail-add]");if(detailAdd){addToCart(detailAdd.dataset.detailAdd);closeModal("#product-modal")}const buyNow=event.target.closest("[data-buy-now]");if(buyNow){addToCart(buyNow.dataset.buyNow);closeModal("#product-modal");openCart()}const review=event.target.closest("[data-review]");if(review)showToast("Review form is ready in the next update")});
document.querySelectorAll("[data-auth-tab]").forEach((tab)=>tab.addEventListener("click",()=>{state.authMode=tab.dataset.authTab;document.querySelectorAll("[data-auth-tab]").forEach((item)=>item.classList.toggle("active",item===tab));$("#auth-name").closest("label").style.display=state.authMode==="signup"?"block":"none";$("#auth-submit").innerHTML=state.authMode==="signup"?"Create account <span>→</span>":"Login securely <span>→</span>"}));
$("#auth-form").addEventListener("submit",async(event)=>{event.preventDefault();const email=$("#auth-email").value.trim();if(!email){showToast("Please enter a valid email");return}try{await supabaseAuth("otp",{email,options:{emailRedirectTo:window.location.href.split("#")[0]}});$("#auth-note").textContent=`Login link sent to ${email}`;showToast("Email check kijiye—login link bhej diya gaya")}catch(error){console.error(error);showToast(error.message||"Email login failed")}});
$("#checkout-btn").addEventListener("click",()=>{if(!state.cart.length){showToast("Your cart is empty");return}const total=state.cart.reduce((sum,item)=>sum+item.price*item.quantity,0);if(total<=0){showToast("Add a valid product before checkout");return}if(state.profile){const fields={name:state.profile.name,phone:state.profile.phone,address:state.profile.address,city:state.profile.city||"",pin:state.profile.pin};Object.entries(fields).forEach(([key,value])=>{const field=$(`#checkout-form [name="${key}"]`);if(field)field.value=value||""})}$("#checkout-total").textContent=rupees(total);closeCart();openModal("#checkout-modal")});
$("#checkout-form").addEventListener("submit",async(event)=>{event.preventDefault();if(!state.cart.length){showToast("Your cart is empty");return}if(!event.target.reportValidity())return;const form=new FormData(event.target),cart=[...state.cart],total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0),customer={name:String(form.get("name")||"").trim(),phone:String(form.get("phone")||"").trim(),address:String(form.get("address")||"").trim(),city:String(form.get("city")||"").trim(),pin:String(form.get("pin")||"").trim(),payment:"cod"};if(total<=0){showToast("Add a valid product before checkout");return}const recentPhoneOrders=state.orders.filter((order)=>order.phone===customer.phone&&order.status!=="Cancelled").length;if(recentPhoneOrders>=3){showToast("This number needs a quick verification before another COD order.");return}if(cart.some((item)=>{const product=products.find((entry)=>entry.id===item.id);return !product||item.quantity>Number(product.stock??0)})){showToast("Some cart items are no longer available");renderProducts();return}const order={id:`AC${Date.now().toString().slice(-6)}`,uuid:crypto.randomUUID(),date:new Date().toLocaleDateString("en-IN"),items:cart.reduce((sum,item)=>sum+item.quantity,0),total,status:"Order Placed",phone:customer.phone,cart};try{await saveOrderToSupabase(order,customer);cart.forEach((item)=>{const product=products.find((entry)=>entry.id===item.id);if(product)product.stock-=item.quantity});state.orders.push(order);state.cart=[];updateCart();save();renderProducts();event.target.reset();closeModal("#checkout-modal");showToast("COD order placed and saved successfully 🎉");renderOrders()}catch(error){console.error(error);showToast("Order save nahi hua. Please try again.")}});
$("#tracking-form").addEventListener("submit",(event)=>{event.preventDefault();const id=String(new FormData(event.target).get("order")||"").trim(),order=state.orders.find((item)=>String(item.id).toLowerCase()===id.toLowerCase());if(!order){$("#tracking-result").innerHTML='<div class="tracking-result">Order not found. Please check the order ID.</div>';return}const steps=["Order Placed","Packed","Shipped","Delivered"],current=steps.indexOf(order.status);if(order.status==="Cancelled"){$("#tracking-result").innerHTML=`<div class="tracking-result"><strong>Order ${order.id}</strong><p class="order-status">Cancelled</p><small>This order has been cancelled.</small></div>`;return}$("#tracking-result").innerHTML=`<div class="tracking-result"><strong>Order ${order.id}</strong><small>Current status: ${order.status}</small><div class="tracking-steps">${steps.map((step,index)=>`<span class="${index<=current?"done":""}">${index<=current?"✓":"○"} ${step}</span>`).join("")}</div></div>`});
$("#chat-toggle").addEventListener("click",()=>$("#chat-box").classList.toggle("open"));
document.querySelector("[data-mobile-shop]").addEventListener("click",()=>$("#products").scrollIntoView({behavior:"smooth"}));
document.querySelectorAll("[data-mobile-cart]").forEach((button)=>button.addEventListener("click",openCart));
document.querySelector("[data-mobile-home]").addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
document.querySelector("[data-mobile-categories]").addEventListener("click",()=>document.querySelector(".category-bar").scrollIntoView({behavior:"smooth"}));
document.querySelector("[data-mobile-search]").addEventListener("click",()=>{$("#search-input").focus();$("#search-input").scrollIntoView({behavior:"smooth",block:"center"})});
document.querySelector("[data-mobile-orders]").addEventListener("click",()=>{renderOrders();openModal("#orders-modal")});
const salesTicker=$("#live-sales-ticker");setInterval(()=>{const names=["Rahul from Lucknow","Priya from Bahraich","Aman from Delhi"];salesTicker.textContent=`✨ ${names[Math.floor(Date.now()/5000)%names.length]} just viewed a popular deal`;},5000);
document.querySelectorAll("[data-chat]").forEach((button)=>button.addEventListener("click",()=>{$("#chat-message").textContent={delivery:"Orders usually arrive in 3–5 business days.",returns:"You can request a return within 7 days.",order:"Open Orders above to view your order status."}[button.dataset.chat]}));
$("#theme-toggle").addEventListener("click",()=>{document.body.classList.toggle("dark-mode");localStorage.setItem("atul-theme",document.body.classList.contains("dark-mode")?"dark":"light")});
if(localStorage.getItem("atul-theme")==="dark")document.body.classList.add("dark-mode");
$("#voice-btn").addEventListener("click",()=>{const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){showToast("Voice search is not supported in this browser");return}const recognition=new SpeechRecognition();recognition.lang="en-IN";recognition.onresult=(event)=>{$("#search-input").value=event.results[0][0].transcript;state.search=$("#search-input").value;renderProducts()};recognition.start();showToast("Listening for a product name…")});
document.querySelectorAll(".footer a").forEach((link)=>link.addEventListener("click",(event)=>{if(link.dataset.policy)return;if(link.getAttribute("href")?.startsWith("#")){event.preventDefault();showToast("This page is coming soon")}}));
window.addEventListener("keydown",(event)=>{if(event.key==="Escape"){document.querySelectorAll(".modal-shell.open").forEach((modal)=>closeModal(`#${modal.id}`));closeCart()}});
async function restoreEmailSession(){const hash=new URLSearchParams(window.location.hash.replace(/^#/,""));const accessToken=hash.get("access_token"),refreshToken=hash.get("refresh_token");if(accessToken){const authenticatedUser=await loadAuthenticatedUser(accessToken);state.user={id:authenticatedUser.id,name:authenticatedUser.user_metadata?.name||authenticatedUser.email||"Atul Cart customer",email:authenticatedUser.email,accessToken,refreshToken};localStorage.setItem("atul-user",JSON.stringify(state.user));window.history.replaceState({},document.title,window.location.pathname);showToast("Email login successful")}if(state.user?.accessToken){try{const authenticatedUser=await loadAuthenticatedUser(state.user.accessToken);state.user={...state.user,id:authenticatedUser.id,email:authenticatedUser.email,name:authenticatedUser.user_metadata?.name||authenticatedUser.email||state.user.name};localStorage.setItem("atul-user",JSON.stringify(state.user));await verifyAdminAccess();await loadProfileFromSupabase()}catch(error){console.error(error);state.isAdmin=false;$("#admin-btn").hidden=true}}updateAccount()}
renderProducts();renderPromoProducts();updateCart();updateAccount();loadProductsFromSupabase();restoreEmailSession().catch((error)=>{console.error(error);showToast("Email login could not be completed")});
let flashSeconds=21600;setInterval(()=>{flashSeconds=Math.max(0,flashSeconds-1);const hours=String(Math.floor(flashSeconds/3600)).padStart(2,"0"),minutes=String(Math.floor((flashSeconds%3600)/60)).padStart(2,"0"),seconds=String(flashSeconds%60).padStart(2,"0");$("#flash-timer").textContent=`${hours}:${minutes}:${seconds}`},1000);
